require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnswersController do

  let(:user) { FactoryGirl.create(:user) }
  let(:node) { FactoryGirl.create(:node) }
  let(:question) { FactoryGirl.create(:question, user: user, node: node ) }
  let(:answer) { FactoryGirl.create(:answer, user: user, question: question ) }
  

  # This should return the minimal set of attributes required to create a valid
  # Answer. As you add validations to Answer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { body: "this is my answer", user: user, question: question }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters.js (e.g. authentication) defined in
  # AnswersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Answer" do
        expect {
          post :create, {:answer => answer, :question_id => question.id }
        }.to change(Answer, :count).by(1)
      end

      xit "assigns a newly created answer as @answer" do
        post :create, {:answer => valid_attributes, :question_id => question.id }
        assigns(:answer).should eq(Answer)
        assigns(:answer).should be_persisted
      end
    end

    describe "with invalid params" do
      xit "assigns a newly created but unsaved answer as @answer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Answer.any_instance.stub(:save).and_return(false)
        post :create, {:answer => valid_attributes, :question_id => question.id }, valid_session
        assigns(:answer).should be_a_new(Answer)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      xit "updates the requested answer" do
        answer = Answer.create! valid_attributes
        # Assuming there are no other answers in the database, this
        # specifies that the Answer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Answer.any_instance.should_receive(:update_attributes).with({ "body" => "MyString" })
        put :update, {:id => answer.to_param, :answer => { "body" => "MyString" }, :question_id => question.id}, valid_session
      end

      it "assigns the requested answer as @answer" do
        answer = Answer.create! valid_attributes
        put :update, {:id => answer.to_param, :answer => valid_attributes, :question_id => question.id }
        assigns(:answer).should eq(answer)
      end

      xit "redirects to the answer" do
        answer = Answer.create! valid_attributes
        put :update, {:id => answer.to_param, :answer => valid_attributes, :question_id => question.id }, valid_session
        response.should redirect_to(answer.question)
      end
    end

    describe "with invalid params" do
      it "assigns the answer as @answer" do
        answer = Answer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Answer.any_instance.stub(:save).and_return(false)
        put :update, {:id => answer.to_param, :answer => { "body" => "invalid value" }, :question_id => question.id}, valid_session
        assigns(:answer).should eq(answer)
      end
    end
  end

  describe "DELETE destroy" do
    xit "destroys the requested answer" do
      answer1 = Answer.create! valid_attributes
      puts "*" * 100
      puts answer1
      puts "*" * 100
      expect {
        delete :destroy, {:id => answer1.to_param, :question_id => question.id}
      }.to change(Answer, :count).by(-1)
    end

    xit "redirects to the answers list" do
      answer = Answer.create! valid_attributes
      delete :destroy, {:id => answer.to_param, :question_id => question.id}, valid_session
      response.should redirect_to(answers_url)
    end
  end

end
